# Podman Compose for Microservices Architecture
# Separate containers for prepare and build services

version: '3'

services:
  # Lightweight prepare service
  # Only handles package resolution and validation
  # No Redis, No Podman, No heavy dependencies
  prepare:
    build:
      context: .
      dockerfile: Containerfile.prepare
    container_name: asu-prepare
    ports:
      - "8001:8001"
    environment:
      - UPSTREAM_URL=${UPSTREAM_URL:-https://downloads.openwrt.org}
      - ASU_SERVICE=prepare
    restart: unless-stopped
    networks:
      - asu-network
    # Minimal resources for lightweight service
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Heavy build service
  # Handles actual firmware building
  # Requires Redis, RQ, Podman access
  build:
    build:
      context: .
      dockerfile: Containerfile.build
    container_name: asu-build
    ports:
      - "8000:8000"
    environment:
      - PUBLIC_PATH=/var/lib/asu/public
      - REDIS_URL=redis://redis:6379
      - UPSTREAM_URL=${UPSTREAM_URL:-https://downloads.openwrt.org}
      - CONTAINER_SOCKET_PATH=/run/podman/podman.sock
      - ALLOW_DEFAULTS=${ALLOW_DEFAULTS:-0}
      - ASU_SERVICE=build
    volumes:
      - ${PUBLIC_PATH:-./public}:/var/lib/asu/public
      - ${CONTAINER_SOCKET_PATH:-/run/user/1000/podman/podman.sock}:/run/podman/podman.sock
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - asu-network
    # More resources for heavy service
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G

  # Redis for build service only
  # Prepare service doesn't need it
  redis:
    image: redis/redis-stack-server:latest
    container_name: asu-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - asu-network

  # Worker for build service
  # Can scale independently
  worker:
    build:
      context: .
      dockerfile: Containerfile.build
    container_name: asu-worker
    command: ["rq", "worker"]
    environment:
      - PUBLIC_PATH=/var/lib/asu/public
      - REDIS_URL=redis://redis:6379
      - UPSTREAM_URL=${UPSTREAM_URL:-https://downloads.openwrt.org}
      - CONTAINER_SOCKET_PATH=/run/podman/podman.sock
    volumes:
      - ${PUBLIC_PATH:-./public}:/var/lib/asu/public
      - ${CONTAINER_SOCKET_PATH:-/run/user/1000/podman/podman.sock}:/run/podman/podman.sock
    restart: unless-stopped
    depends_on:
      - redis
      - build
    networks:
      - asu-network
    deploy:
      replicas: 2  # Can scale workers independently
      resources:
        limits:
          cpus: '2'
          memory: 2G

  # Optional: Reverse proxy / Load balancer
  # Routes /api/v1/build/prepare → prepare service
  # Routes /api/v1/build → build service
  nginx:
    image: nginx:alpine
    container_name: asu-nginx
    ports:
      - "80:80"
    volumes:
      - ./misc/nginx-microservices.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - prepare
      - build
    restart: unless-stopped
    networks:
      - asu-network

networks:
  asu-network:
    driver: bridge

volumes:
  redis-data:
