[tool.poetry]
name = "asu"
version = "0.0.0"
description = "An image on demand server for OpenWrt based distributions"
authors = ["Paul Spooren <mail@aparcar.org>"]
license = "GPL-2.0"
readme = "README.md"
include = ["asu/branches.yml"]

[tool.poetry.dependencies]
python = "^3.8.1"
PyNaCl = "^1.5.0"
redis = "^4.1.1"
requests = "^2.27.1"
rq = "^1.10.1"
connexion = {extras = ["swagger-ui"], version = "^2.12.0"}
prometheus-client = "^0.13.1"
pytest-cov = "^3.0.0"
urlpath = "^1.2.0"
setuptools = "^65.4.1"
podman = "^4.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
pytest-httpserver = "^1.0.3"
fakeredis = "^1.7.1"
black = "^22.1.0"
coverage = "^6.3.2"
isort = "^5.10.1"
bandit = "^1.7.4"
pylint = "^2.15.4"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
