name: Upload Python Package and Docker Container

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Set __version__ and poetry version
      run: |
        TAG="$(git describe --tags --abbrev=0)"
        echo "TAG=$TAG" >> "$GITHUB_ENV"
        echo "__version__ = \"$TAG\"" > asu/__init__.py
        poetry version "$TAG"

    - name: Build and publish
      run: |
        poetry build
        poetry publish \
          --username  ${{ secrets.PYPI_USERNAME }} \
          --password ${{ secrets.PYPI_PASSWORD }}

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push ASU server to Docker Hub
      uses: docker/build-push-action@v2
      with:
        tags: |
          aparcar/asu-server:latest
          aparcar/asu-server:$TAG
        file: Dockerfile.server
        push: true

    - name: Push ASU worker to Docker Hub
      uses: docker/build-push-action@v2
      with:
        tags: |
          aparcar/asu-worker:latest
          aparcar/asu-worker:$TAG
        file: Dockerfile.worker
        push: true
